### ISSUE TITLE
Yanked versions on Github

### ISSUE THREAD

**Issue by aecorn** [zen-xu/pyarrow-stubs#141]
Hi, I had a poetry install fail because of poetry failing to resolve the naming convention used on Pypi I think.
I later discovered that there are two yanked versions of the package on Pypi that are sorted to the top.

The error I got was `Unable to find installation candidates for pyarrow-stubs (20240828)`

Maybe this was caused by depending on an earlier yanked version?

https://pypi.org/project/pyarrow-stubs/#history

**Comment by zen-xu** [comment]
Can you use version `17.xx`? The timestamp version style has been deprecated
