### ISSUE TITLE
Stubs have type parameter where implementation doesn't

### ISSUE THREAD

**Issue by ben-freist** [zen-xu/pyarrow-stubs#155]
Hey,
I've had some issues with the type annotations for code that uses pyarrow. The problem is:
```
import pyarrow as pa
def func() -> pa.Field:
    return pa.field('x', pa.string())
```

Here mypy complains about the missing type parameter for `Field`. If I add `Any` as a type parameter then I get an error at runtime saying that the type object is not subscritable.

In pyarrow https://github.com/apache/arrow/blob/b907c5dadb516b525c8fafbf34b0116d44044733/python/pyarrow/types.pxi#L2431
and the corresponding declaration in pyarrow-stubs:
https://github.com/zen-xu/pyarrow-stubs/blob/a2380d0bc6d3a2ea19261b3f2161d3ce191adf9b/pyarrow-stubs/__lib_pxi/types.pyi#L267

The same happens for `pyarrow.MapType` and `pyarrow.ListType`.

**Comment by zen-xu** [comment]
<img width="972" alt="image" src="https://github.com/user-attachments/assets/23b632a2-85ff-41af-b30b-0a1c20382f20">
You just need to omit the return type, or quote the return type
