### ISSUE TITLE
NativeFile doesn't fit SupportsRead protocol

### ISSUE THREAD

**Issue by yaxxie-piramidal** [zen-xu/pyarrow-stubs#162]
Hello, thanks for the stubs package.

The stub for `NativeFile` doesn't seem to match the [provided signature](https://arrow.apache.org/docs/python/generated/pyarrow.NativeFile.html#pyarrow.NativeFile.read) against the documentation for the read method:

https://github.com/zen-xu/pyarrow-stubs/blob/b1edf35d7fe23ba97a0057a878340a13b7f77a9f/pyarrow-stubs/__lib_pxi/io.pyi#L51-L53

This prevents typechecker from seeing `NativeFile` as `SupportsRead`.

**Comment by zen-xu** [comment]
Thanks for find this issue, and I will fix it
