### ISSUE TITLE
StructArray.from_arrays takes sequence of array

### ISSUE THREAD

**Issue by tekumara** [zen-xu/pyarrow-stubs#42]
See
1. https://arrow.apache.org/docs/python/generated/pyarrow.StructArray.html#pyarrow.StructArray.from_arrays
2. https://github.com/apache/arrow/blob/e61c105c73dfabb51d5afc972ff21cc5326b3d93/python/pyarrow/array.pxi#L4015

**Comment by zen-xu** [comment]
resolved by #35
