### ISSUE TITLE
Support temporal pyarrow.compute functions

### ISSUE THREAD

**Issue by tekumara** [zen-xu/pyarrow-stubs#45]
Support temporal pyarrow.compute functions, see https://arrow.apache.org/docs/cpp/compute.html#type-categories

eg:

* [pc.floor_temporal](https://arrow.apache.org/docs/python/generated/pyarrow.compute.floor_temporal.html)
* [pc.subsecond](https://arrow.apache.org/docs/python/generated/pyarrow.compute.subsecond.html)

(you may already be considering this as part of the rewrite, if so, thank you!)

**Comment by zen-xu** [comment]
see #35
