### ISSUE TITLE
pyarrow.parquet.write_table mypy failures since 17.0

### ISSUE THREAD

**Issue by rainsville** [zen-xu/pyarrow-stubs#97]
Since the refactor in https://github.com/zen-xu/pyarrow-stubs/pull/35, we are getting mypy failures for code that runs correctly:

```python
from io import BytesIO

import pyarrow
import pyarrow.parquet as pyparquet

writer = pyarrow.BufferOutputStream()
table = pyarrow.Table.from_pandas(dataframe)
pyparquet.write_table(table=table, where=writer, compression="GZIP")
buffer = BytesIO(writer.getvalue())
```

error: Argument "where" to "write_table" has incompatible type "BufferOutputStream"; expected "str | Path | IO[Any]"  [arg-type]
error: Argument "compression" to "write_table" has incompatible type "Literal['GZIP']"; expected "Literal['gzip', 'bz2', 'brotli', 'lz4', 'lz4_frame', 'lz4_raw', 'zstd', 'snappy']"  [arg-type]
error: Argument 1 to "BytesIO" has incompatible type "pyarrow.__lib_pxi.io.Buffer"; expected "_collections_abc.Buffer"  [arg-type]

**Comment by zen-xu** [comment]
error1: fixed in #98
error2: use `gzip`
